name: Chekov Demo

on:
  workflow_dispatch:    

jobs:
  chekov-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Chekov
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
